services:
    backend:
        build:
            context: flask
            target: builder
        depends_on:
            - mongo
        environment:
            - FLASK_SERVER_PORT=9091
        stop_signal: SIGINT
        volumes:
            - ./flask:/src
    elasticsearch:
        environment:
            discovery.type: single-node
        image: elasticsearch:7.16.1
        ports:
            - 9300:9300
    haproxy:
        command: sh -c 'haproxy -f /usr/local/etc/haproxy/haproxy.cfg -d -q -S /dev/stdout 2>&1 | tee -a /var/log/haproxy/haproxy.log'
        image: haproxy
        ports:
            - 59575:59575
            - 59570:59570
        volumes:
            - ./logs:/var/log/haproxy
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    logstash:
        environment:
            discovery.seed_hosts: elasticsearch
        image: logstash:7.16.1
        ports:
            - 9600:9600
        volumes:
            - ./logs/haproxy.log:/home/haproxy.log
            - ./logstash.config:/usr/share/logstash/pipeline/logstash-nginx.config
    mongo:
        image: mongo
    web:
        command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - backend
        environment:
            - FLASK_SERVER_ADDR=haproxy:59570
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/tmp/nginx.conf
